### PR TITLE
Fix typo in _posts/2018-01-30-quicli.md

### PR DESCRIPTION
**Pull request by mgattozzi**
Woops :P

### CODE REVIEW

**Comment by killercup** [comment]
Lol I added *one* sentence xD

**Comment by mgattozzi** [comment]
Stop writing on trains!

**Comment by killercup** [comment]
Sorry, what? I couldn't hear you, I'm in a bus

Michael Gattozzi <notifications@github.com> schrieb am Mi. 31. Jan. 2018 um
15:39:

**Comment by mgattozzi** [comment]
What I couldn't understand you cause your words got all messed up since you're writing on a bus

**Pull request merged**
